version: '3.8'

services:
  spring-app:
    build: .
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/estacionamento
    ports:
      - '8080:8080'
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
